### ISSUE TITLE
module missing

### ISSUE THREAD

**Issue by ovk81** [jasp-stats/jaspDescriptives#306]
I have a problem installing JASP. Have tried it a couple of times and get the error message that bundled module wasn't correctly installed and cannot be loaded. 
![error](https://github.com/user-attachments/assets/11ebd158-d36f-4173-8413-6f408d3f3f05)

**Comment by shun2wang** [comment]
Hi @ovk81 Please report a bug at here: https://github.com/jasp-stats/jasp-issues/issues and give us more infomation to know what happend. thanks.

**Comment by tomtomme** [comment]
And maybe try installation via the Microsoft store. Thx
